# Collinear PDF set and member to be used for the generation of the
# tables. They are assumed to be in the LHAPDF format.
pdfset:
  name: "MMHT2014nnlo68cl"
  member: 0

# Collinear FF set and member to be used for the generation of the
# tables. They are assumed to be in the LHAPDF format.
ffset:
  name: "DSS14_NLO_Pip"
  member: 0

# Name of the b* prescription. This name has to correspond to a
# function in inc/NangaParbat/bstar.h
bstar: bstarmin

# Perturbative order of the computation. 0: LL, 1: NLL, 2: NNLL, 3:
# NNNLL, -1: NLL', -2: NNLL'
PerturbativeOrder: 3

# Initial and final scale-variation factors around mub = 2e^{-gamma_E}
# / b and Q, respectively.
TMDscales:
  Ci: 1
  Cf: 1

# Reference value of alpha_em.
alphaem:
  aref: 0.00776578395589
  Qref: 91.1876
  run: true

# Parameters of the x-space subgrids on which collinear PDFs are
# tabulated.
xgridpdf:
  - [60, 1e-4, 3]
  - [60, 1e-1, 3]
  - [50, 6e-1, 3]
  - [50, 8e-1, 3]

# Parameters of the x-space subgrids on which collinear FFs are
# tabulated.
xgridff:
  - [60, 1e-2, 3]
  - [50, 6e-1, 3]
  - [50, 8e-1, 3]

# Maximum number of Ogata-quadrature points (no more than 1000).
nOgata: 200

# Number of points, interpolation degree, and integration accuracy of
# the grid in Q.
Qgrid:
  n: 4
  InterDegree: 3
  eps: 1e-3

# Number of points, interpolation degree, and integration accuracy of
# the grid in xi = exp(y) or xF (depending on the observable).
xigrid:
  n: 4
  InterDegree: 3
  eps: 1e-3

# Number of points, interpolation degree, and integration accuracy of
# the grid in x (SIDIS).
xbgrid:
  n: 4
  InterDegree: 3
  eps: 1e-3

# Number of points, interpolation degree, and integration accuracy of
# the grid in z (for SIDIS).
zgrid:
  n: 4
  InterDegree: 3
  eps: 1e-3

# Maximum value allowed for the ratio qT / Q. This has to be intended
# as a "generation-level" cut meaning that only data points with qT /
# Q below this value are generated. Those above are simply set to
# zero. However, a more restrictive cut can still be applied at the
# fit level. This avoids computing predictions for points whose
# kinematics is such that TMD factorisation is not valid.
qToverQmax: 3.5
